GET   http://localhost:3000/auth/getUsers


###
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "email" : "test@gmail.com",
    "username" : "test",
    "password" : "123"
}

###
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "lutfiapriamto12@gmail.com",
    "password" : "12345"
}
###
GET   http://localhost:3000/auth/667e6f2c0951e8fe53a88a04/getUserByID

###
GET http://localhost:3000/auth/getUserByUsername?username=test123

###


###
POST  http://localhost:3000/auth/suggestion
Content-Type: application/json

{
    "email" : "lutfiapriamto12@gmail.com",
    "suggestions" : [
        {
            "modulename" : "kontil",
            "suggestion" : "kolsku"
        }
    ]
}

###
POST  http://localhost:3000/auth/submitresult
Content-Type: application/json

{
    "email" : "lutfiapriamto12@gmail.com",
    "quiz" : [
        {
            "quizname" : "test",
            "score" : 80
        }
    ]
}

###


























GET   http://localhost:3000/admin/getAdmins

###

POST  http://localhost:3000/admin/registerAdmin
Content-Type: application/json

{
    "username" : "test123",
    "password" : "123"
}

###

POST  http://localhost:3000/admin/loginAdmin
Content-Type: application/json

{
    "username" : "test123",
    "password" : "123"
}


###











































GET   http://localhost:3000/modules/getModules

###
GET   http://localhost:3000/modules/667a3b50612e631e08cc7af4/getModulesByID

###

POST  http://localhost:3000/modules/addModules
Content-Type: application/json

{
    "judul" : "babi",
    "link" : "kunci",
    "desc" : "blalallala"
}

###
PATCH    http://localhost:3000/modules/667d0db79c4433628fedc66c/updateModule
Content-Type: application/json

{
    "judul" : "ini lagi di edit dan edit lagi",
    "link" : "bubbbb",
    "desc" : "kdsakiw"
}

###

DELETE     http://localhost:3000/modules/667d12f82742fde6673345dc/deleteModule

































###

